### ISSUE TITLE
Module 1, Page 4: Video-How -to-do-it,  Video Display

### ISSUE THREAD

**Issue by mcs160** [bke858/math-whiz#43]
Video displays title over the writing for the first minute; you cannot see example clearly.  Recommend moving writing more towards the center so that it is not overwritten.
![screen shot 2016-11-16 at 6 31 51 pm](https://cloud.githubusercontent.com/assets/22204137/20371558/4322a77e-ac2b-11e6-8832-d6f176e36f17.png)

**Comment by ylp290** [comment]
will fix
